version: "2"
services:
  public:
    build: .
    ports:
      - "4008:4008"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    expose:
      - "4008"
    environment:
      - PORT=4008